#!/bin/bash
# Define Neovim applications you want to experiment with.

# The repository cloned must bootstrap itself.  In otherwords, clone and nvim
# is all that is needed.
#
# Column definitions:
# alias:
#   The Neovim name you desire to install, reset, set as your default, or delete.
#   Your selection is written to ~/.config/nvims/nvim_appname as:
#
#   alias nvim-{alias}="NVIM_APPNAME=nvim-{alias} nvim
#
# sn:
#   The literal short-name alias to emit alongside the primary alias.
#   Empty means no short name. Any non-empty value is written as:
#
#   alias {sn}="NVIM_APPNAME=nvim-{alias} nvim"
#
#   Conventionally use the distro's own name (e.g. traap|...|traap), or pick a
#   shorter alias if you prefer (e.g. LazyVim|...|lv).
#
# URL:
#   The name is appended to github.com.  The fully-qualified URL becomes:
#
#   https://github.com/{URL}.git
#
# branch
#   Branch can be any of the following.
#   1. default whatever your default branch name is.
#   2. Anythig else is activated with git check out so it can be a
#      a. branc name
#      b. git commit
#      c. tag
#      d. release
#
# alias       | sn        | URL                     | branch
readonly neovim_distros=(
  "default    |          | none                    | none"
  "astro      |          | AstroNvim/template      | default"
  "asyncedd   |          | asyncedd/dots.nvim      | default"
  "barebones  |barebones | Traap/barebones         | default"
  "barelazy   |barelazy  | Traap/barebones         | lazy"
  "baretmux   |baretmux  | Traap/barebones         | tmux"
  "cam        |          | ChristianChiarulli/nvim | default"
  "CyberNvim  |          | pgosar/CyberNvim        | default"
  "exos       |          | exosyphon/nvim          | none"
  "kickstart  |          | nvim-lua/kickstart.nvim | default"
  "launch     |          | LunarVim/Launch.nvim    | default"
  "LazyVim    |LazyVim   | LazyVim/starter         | default"
  "lervag     |          | lervag/dotnvim          | default"
  "NormalNvim |          | NormalNvim/NormalNvim   | default"
  "nvchad     |          | NvChad/starter          | default"
  "nvconf     |          | TechnicalDC/NvConf      | default"
  "OVIwrite   |          | MiragianCycle/OVIWrite  | default"
  "prime      |          | Traap/init.lua          | default"
  "pwnvim     |          | pwnwriter/pwnvim        | default"
  "traap      |traap     | Traap/nvim              | default"
  "starter    |          | lazyvim/starter         | default"
  "vapour     |          | Traap/VapourNvim        | default"
  "void       |          | nvoid-lua/nvoid         | default"
  "whiskey    |whiskey   | Traap/nvim              | 706377a"
  "xray       |xray      | Traap/nvim              | v0.9.5-lazyvim"
  "zero       |zero      | Traap/lazy.zero         | default"
  "zulu       |zulu      | Traap/nvim              | v0.6.8-packer"
)
